name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Ensure CNAME file exists
        run: echo 'altaiyeb.info' > ./dist/CNAME

      - name: Configure Git
        run: |
          git config --global user.name 'aimenAlt'
          git config --global user.email 'ymnghost@gmail.com'

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/aimenAlt/mount-folio.git
          npm run deploy
