name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace 'master' with your default branch name if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'aimenAlt'
          git config --global user.email 'ymnghost@gmail.com'

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Use the PAT stored as a secret
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/aimenAlt/mount-folio.git
          npm run deploy
